In [8]:
import numpy as np
import scipy 
import scipy.linalg
np.set_printoptions(precision=2, suppress=True)

### 1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей
$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [15]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


Координаты первого вектора (-0.89, 0.45) удовелетворяют найденному "на листочке" соотношению $x_1=-2*x_2$, т.е коллинеарен вектору (2, -1).

Координаты второго вектора (0.83, -0.55) удовелетворяют найденному "на листочке" соотношению $2*x_1=-3*x_2$, т.е коллинеарен вектору (3, -2)

###  2. Дан оператор поворота на 180 градусов, задаваемый матрицей 
$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$
#### Показать, что любой вектор является для него собственным.

In [17]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


Мы получили, что координаты собственных векторов - координаты базиса двумерного пространства, что означает, что любой вектор будет для заданной матрицы собственным.

###  3. Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

#### Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

In [44]:
a = np.array([[1, 1], [-1, 3]])
x = np.array([1, 1])
print(f'Матрица A\n{a}\n')
print(f'Матрица X\n{x}\n')

print(f'Матрица AX\n{np.dot(a, x)}')

Матрица A
[[ 1  1]
 [-1  3]]

Матрица X
[1 1]

Матрица AX
[2 2]


При решении уравнения $A*X=l*X$ получаем, что $l=2$. Что означает, что вектор $x=(1,1)$ является собственным вектором этого линейного оператора

###  4. Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

#### Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [47]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([3, -3, -4])
print(f'Матрица A\n{a}\n')
print(f'Матрица X\n{x}\n')

print(f'Матрица AX\n{np.dot(a, x)}')

Матрица A
[[0 3 0]
 [3 0 0]
 [0 0 3]]

Матрица X
[ 3 -3 -4]

Матрица AX
[ -9   9 -12]


При решении уравнения $A*X=l*X$ получаем, что $l=-3$ или $l=3$. Что означает, что вектор $x=(3,-3, 4)$ __не__ является собственным вектором этого линейного оператора